### ISSUE TITLE
Add product Issue

### ISSUE THREAD

**Issue by tanzeelazad95** [reactioncommerce/reaction-admin#308] opened 2020-08-12 11:02 UTC
## Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you able to consistently reproduce the issue?

## Issue Description
"When we update a product, we saved the changes and then it requires us to publish it. But, we need to 
refresh page 2-3 times to see the publish button."

## Steps to Reproduce
1. Login to reactipon
2. Go to products page
3. Update a product and save changes

You will see that the publish button is not enabling immediately and you have to refresh the page multiple times.
## Possible Solution
The publish button should be enabled immediately

### System Information
We are getting this error on multiple systems:

- MAC OS Catalina
- Ubuntu 20.04 LTS

**Comment by kieckhafer** [comment] 2020-08-21 21:53
Thanks for the reported issue, @tanzeelazad95.

The `reaction-development-platform` repository is used to bootstrap the project and get it up and running, but issues regarding the API, Admin, Storefront, or anything outside the initial build are better suited in their respective project repositories.

I'm going to move this issue to the `reaction-admin` repo.

**Comment by brent-hoover** [comment] 2020-10-02 08:33
We're seeing this issue as well in production

**Comment by loan-laux** [comment] 2021-02-28 11:11
I think this issue was a duplicate of https://github.com/reactioncommerce/reaction-admin/issues/251. It seems to be fixed by @jrw421's PR https://github.com/reactioncommerce/reaction-admin/pull/347. I can't reproduce it anymore. 🎉

**Closed as completed** 2021-03-01 16:02 UTC
Labels: bug, verified reproducible
