### ISSUE TITLE
Make init-dev command in reaction-development-platform doesn't work 

### ISSUE THREAD

**Issue by Prodigy343** [reactioncommerce/reaction-admin#281] opened 2020-05-18 19:00 UTC
## Issue Description
I'm trying to setting up the environment development but the admin container get down after 2 minutes and the log of the container says:

Failed to reset plugins file at /usr/local/src/app/client/plugins.js (image below)
![image](https://user-images.githubusercontent.com/19996197/82170376-3b8d8900-9892-11ea-9866-cfc2241930a0.png)

The other containers looks good.

Thanks in advance.

## Steps to Reproduce
1. git clone git@github.com:reactioncommerce/reaction-development-platform.git
2. cd reaction-development-platform
3. make init-dev

### Versions
3.7.1

**Comment by Eduard-Hasa** [comment] 2020-10-01 08:19
Any info on this? I have been beyond stuck on this and desperate to figure it out.

**Comment by TarasKryvko** [comment] 2020-10-07 12:55
> Any info on this? I have been beyond stuck on this and desperate to figure it out.

Hey, have you found any solution so far?

**Comment by krauss** [comment] 2020-10-07 21:28
Hey guys, I am experiencing a similar problem. The only container that exists is the `reaction-admin`. But the error I get is the following:

![reaction_admin_error](https://user-images.githubusercontent.com/797962/95389834-c404d880-08ca-11eb-90c8-6d6055f4d3af.png)

Has anyone had any solution?

**Comment by krauss** [comment] 2020-10-10 00:13
Hey lads, I recommend you to pass the `--verbose` argument where `npm install` is called, which is probably on the **docker-compose.dev.yml** file.

Then run: 
* `make clean-reation-admin` and then 
* `make init-dev-reaction-admin`. 
* `cd reaction-admin` and capture the container logs through `docker-compose logs -f`

That will **not** fix the problem, but it will help with the diagnostic. 

Cheers!

**Comment by balibebas** [comment] 2020-10-10 12:09
@Prodigy343 Are you still experiencing this issue? Running `init-dev` on everything—is that really what you're looking for? Or are you simply trying to develop one of the projects? TBH I don't see this issue ever getting resolved with the amount of information provided if the problem cannot be reproduced by others (and it looks like that may be the case based on the number of thumbs-up emojis on the OP).

**Comment by krauss** [comment] 2020-10-10 19:53
Guys I had a similar problem, as I mentioned before and **I fixed it by removing the export part of the `command:` line** from the reaction-admin docker-compose.dev.yml file, like this:

```javascript
command: bash -c "npm install --no-audit && node ./.reaction/waitForMongo.js && node --experimental-modules ./.reaction/scripts/run.mjs"
```
After editing the `docker-compose-dev.yml`, I did `make clean-raction-admin` and then `make init-dev-reaction-admin`

If you look into the Dockerfile-dev for reaction-admin, you will notice that such export is already done there. So that's why I removed it from the docker-compose command. It fixed my problems. I hope it fixes yours too!

**Comment by Akarshit** [comment] 2021-01-21 02:41
I am trying to reproduce this one on OSX, but am unable to do so. If anyone has some pointers on how to reproduce this one, let me know, please.

**Comment by nazzrim** [comment] 2021-01-25 13:24
I can reproduce the bug on my Ubuntu 18.04.5 LTS machine.
After cloning the repository checkout reaction.
`make checkout-reaction`
Afterwards change api-core version in `./reaction/package.json` from 1.4.2 to 1.4.3 (see [reactioncommerce/reaction-development-platform#165](https://github.com/reactioncommerce/reaction-development-platform/issues/165)) and start everything with `make init-dev`.

**Comment by nazzrim** [comment] 2021-01-25 13:47
> Hey lads, I recommend you to pass the `--verbose` argument where `npm install` is called, which is probably on the **docker-compose.dev.yml** file.
> 
> Then run:
> 
> * `make clean-reation-admin` and then
> * `make init-dev-reaction-admin`.
> * `cd reaction-admin` and capture the container logs through `docker-compose logs -f`
> 
> That will **not** fix the problem, but it will help with the diagnostic.
> 
> Cheers!

This is the last part of the reaction-admin container logs with --verbose added to npm install.

```
[...]
Use styled-components at work? Consider supporting our development efforts at opencollective.com/styled-components
npm verb lifecycle styled-components@3.4.2~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle styled-components@3.4.2~postinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/src/app/node_modules/styled-components/node_modules/.bin:/usr/local/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/node/.meteor
npm verb lifecycle styled-components@3.4.2~postinstall: CWD: /usr/local/src/app/node_modules/styled-components
npm info lifecycle subscriptions-transport-ws@0.9.16~postinstall: subscriptions-transport-ws@0.9.16
npm info lifecycle sweetalert2@7.33.1~postinstall: sweetalert2@7.33.1
npm info lifecycle tether-tooltip@1.2.0~postinstall: tether-tooltip@1.2.0
npm info lifecycle transliteration@2.1.11~postinstall: transliteration@2.1.11
npm info lifecycle url@0.11.0~postinstall: url@0.11.0
npm info lifecycle wait-for-expect@1.3.0~postinstall: wait-for-expect@1.3.0
npm info lifecycle wait-on@4.0.2~postinstall: wait-on@4.0.2
npm timing action:postinstall Completed in 2021ms
npm verb unlock done using /home/node/.npm/_locks/staging-5e4a8f95ac9c8f8d.lock for /usr/local/src/app/node_modules/.staging
npm timing stage:executeActions Completed in 68437ms
npm timing stage:rollbackFailedOptional Completed in 7ms
npm info linkStuff reaction-admin@3.0.0-beta.11
npm info lifecycle reaction-admin@3.0.0-beta.11~install: reaction-admin@3.0.0-beta.11
npm info lifecycle reaction-admin@3.0.0-beta.11~postinstall: reaction-admin@3.0.0-beta.11
npm info lifecycle reaction-admin@3.0.0-beta.11~prepublish: reaction-admin@3.0.0-beta.11
npm info lifecycle reaction-admin@3.0.0-beta.11~prepare: reaction-admin@3.0.0-beta.11
npm timing stage:runTopLevelLifecycles Completed in 76423ms
npm verb saving []
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

added 1797 packages from 1243 contributors in 80.022s

57 packages are looking for funding
  run `npm fund` for details

npm verb exit [ 0, true ]
npm timing npm Completed in 82351ms
npm info ok
Waiting for MongoDB...
MongoDB ready.
Waiting for MongoDB replica set...
MongoDB replica set ready.
(node:1) ExperimentalWarning: The ESM module loader is experimental.
Setting up plugin imports...

Failed to reset plugins file at /usr/local/src/app/client/plugins.js
```

Not sure if this matters, but there is no plugins.js file in the `./reaction-admin/client/` folder.

**Comment by gurvancampion** [comment] 2021-03-03 08:04
> Guys I had a similar problem, as I mentioned before and **I fixed it by removing the export part of the `command:` line** from the reaction-admin docker-compose.dev.yml file, like this:
> 
> ```js
> command: bash -c "npm install --no-audit && node ./.reaction/waitForMongo.js && node --experimental-modules ./.reaction/scripts/run.mjs"
> ```
> 
> After editing the `docker-compose-dev.yml`, I did `make clean-raction-admin` and then `make init-dev-reaction-admin`
> 
> If you look into the Dockerfile-dev for reaction-admin, you will notice that such export is already done there. So that's why I removed it from the docker-compose command. It fixed my problems. I hope it fixes yours too!

I had a similar problem with an error about the export PATH and it also worked for me by removing it, running Ubuntu 20.04.1 LTS in WSL2.

After that I have the same problem as @nazzrim:
```js
> reaction-admin@3.0.0-beta.12 postinstall /usr/local/src/app

> is-ci || is-docker || husky install


npm WARN saveError EACCES: permission denied, open '/usr/local/src/app/package.json.1512109529'

npm WARN @reactioncommerce/catalyst@1.19.1 requires a peer of react-dom@~16.9.0 but none is installed. You must install peer dependencies yourself.

npm WARN mdi-material-ui@5.8.0 requires a peer of @material-ui/core@^1.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN @reactioncommerce/components@0.69.0 requires a peer of react@~16.9.0 but none is installed. You must install peer dependencies yourself.

npm WARN @reactioncommerce/components@0.69.0 requires a peer of react-stripe-elements@~2.0.1 but none is installed. You must install peer dependencies yourself.

npm WARN @reactioncommerce/components@0.69.0 requires a peer of reacto-form@~1.4.0 but none is installed. You must install peer dependencies yourself.

npm WARN @reactioncommerce/components@0.69.0 requires a peer of styled-components@~3.3.3 but none is installed. You must install peer dependencies yourself.

npm WARN @reactioncommerce/eslint-config@2.1.1 requires a peer of eslint-plugin-jest@>=23 but none is installed. You must install peer dependencies yourself.

npm WARN frontend-collective-react-dnd-scrollzone@1.0.2 requires a peer of react-dnd@^7.3.0 but none is installed. You must install peer dependencies yourself.

npm WARN graphql-tag@2.9.2 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

npm WARN jss-camel-case@6.1.0 requires a peer of jss@^9.7.0 but none is installed. You must install peer dependencies yourself.

npm WARN jss-compose@5.0.0 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN jss-default-unit@8.0.2 requires a peer of jss@^9.4.0 but none is installed. You must install peer dependencies yourself.

npm WARN jss-expand@5.3.0 requires a peer of jss@^9.4.0 but none is installed. You must install peer dependencies yourself.

npm WARN jss-extend@6.2.0 requires a peer of jss@^9.7.0 but none is installed. You must install peer dependencies yourself.

npm WARN jss-global@3.0.0 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN jss-nested@6.0.1 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN jss-preset-default@4.5.0 requires a peer of jss@^9.7.0 but none is installed. You must install peer dependencies yourself.

npm WARN jss-props-sort@6.0.0 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN jss-template@1.0.1 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN jss-vendor-prefixer@7.0.0 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.

npm WARN react-sortable-tree@2.7.1 requires a peer of react-dnd@^7.3.0 but none is installed. You must install peer dependencies yourself.

npm WARN react-test-renderer@16.13.1 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


up to date in 26.257s


74 packages are looking for funding

run `npm fund` for details


Waiting for MongoDB...

MongoDB ready.

Waiting for MongoDB replica set...

MongoDB replica set ready.

(node:1) ExperimentalWarning: The ESM module loader is experimental.

Setting up plugin imports...


Failed to reset plugins file at /usr/local/src/app/client/plugins.js
```

**Comment by m5ingh** [comment] 2021-05-13 20:12
anybody able to solve this? same status as @nazzrim and @gurvan-guss. 
maybe @Akarshit  can give any workaround to put admin in dev mode? 
also how come docker dev builds are successful on some machine while not on other machines using the same docker config files.
what exactly is meant by this error. Does this mean that the loader is not able to find the specified file or the loader failed somehow?

> failed to reset plugins file at /usr/local/src/app/client/plugins.js

logs:

> Attaching to reaction-admin_reaction-admin_1
reaction-admin_1  | npm info it worked if it ends with ok
reaction-admin_1  | npm verb cli [
reaction-admin_1  | npm verb cli   '/usr/local/bin/node',
reaction-admin_1  | npm verb cli   '/usr/local/bin/npm',
reaction-admin_1  | npm verb cli   'install',
reaction-admin_1  | npm verb cli   '--no-audit',
reaction-admin_1  | npm verb cli   '--verbose'
reaction-admin_1  | npm verb cli ]
reaction-admin_1  | npm info using npm@6.13.4
reaction-admin_1  | npm info using node@v12.16.1
reaction-admin_1  | npm verb npm-session 74632b253f6be685
reaction-admin_1  | npm info lifecycle reaction-admin@3.0.0-beta.13~preinstall: reaction-admin@3.0.0-beta.13
reaction-admin_1  | npm timing stage:loadCurrentTree Completed in 1644ms
reaction-admin_1  | npm timing stage:loadIdealTree:cloneCurrentTree Completed in 19ms
reaction-admin_1  | npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1149ms
reaction-admin_1  | npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 1328ms
reaction-admin_1  | npm timing stage:loadIdealTree Completed in 2957ms
reaction-admin_1  | npm timing stage:generateActionsToTake Completed in 218ms
reaction-admin_1  | npm verb correctMkdir /home/node/.npm/_locks correctMkdir not in flight; initializing
reaction-admin_1  | npm verb lock using /home/node/.npm/_locks/staging-5e4a8f95ac9c8f8d.lock for /usr/local/src/app/node_modules/.staging
reaction-admin_1  | npm http fetch GET 200 https://registry.npmjs.org/fsevents/-/fsevents-1.2.13.tgz 478ms
reaction-admin_1  | npm http fetch GET 200 https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz 484ms
reaction-admin_1  | npm timing action:extract Completed in 493ms
reaction-admin_1  | npm timing action:finalize Completed in 3ms
reaction-admin_1  | npm timing action:refresh-package-json Completed in 4ms
reaction-admin_1  | npm timing action:preinstall Completed in 1ms
reaction-admin_1  | npm timing action:build Completed in 0ms
reaction-admin_1  | npm timing action:install Completed in 1ms
reaction-admin_1  | npm timing action:postinstall Completed in 0ms
reaction-admin_1  | npm verb unlock done using /home/node/.npm/_locks/staging-5e4a8f95ac9c8f8d.lock for /usr/local/src/app/node_modules/.staging
reaction-admin_1  | npm timing stage:executeActions Completed in 506ms
reaction-admin_1  | npm timing stage:rollbackFailedOptional Completed in 4ms
reaction-admin_1  | npm info linkStuff reaction-admin@3.0.0-beta.13
reaction-admin_1  | npm info lifecycle reaction-admin@3.0.0-beta.13~install: reaction-admin@3.0.0-beta.13
reaction-admin_1  | npm info lifecycle reaction-admin@3.0.0-beta.13~postinstall: reaction-admin@3.0.0-beta.13
reaction-admin_1  | 
reaction-admin_1  | > reaction-admin@3.0.0-beta.13 postinstall /usr/local/src/app
reaction-admin_1  | > is-ci || is-docker || husky install
reaction-admin_1  | 
reaction-admin_1  | npm verb lifecycle reaction-admin@3.0.0-beta.13~postinstall: unsafe-perm in lifecycle true
reaction-admin_1  | npm verb lifecycle reaction-admin@3.0.0-beta.13~postinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/usr/local/src/app/node_modules/.bin:/home/node/.meteor
reaction-admin_1  | npm verb lifecycle reaction-admin@3.0.0-beta.13~postinstall: CWD: /usr/local/src/app
reaction-admin_1  | npm info lifecycle reaction-admin@3.0.0-beta.13~prepublish: reaction-admin@3.0.0-beta.13
reaction-admin_1  | npm info lifecycle reaction-admin@3.0.0-beta.13~prepare: reaction-admin@3.0.0-beta.13
reaction-admin_1  | npm timing stage:runTopLevelLifecycles Completed in 5438ms
reaction-admin_1  | npm verb saving []
reaction-admin_1  | npm verb shrinkwrap skipping write for package.json because there were no changes.
reaction-admin_1  | npm info lifecycle undefined~preshrinkwrap: undefined
reaction-admin_1  | npm info lifecycle undefined~shrinkwrap: undefined
reaction-admin_1  | npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
reaction-admin_1  | npm info lifecycle undefined~postshrinkwrap: undefined
reaction-admin_1  | npm WARN @apollo/react-common@3.1.4 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @apollo/react-components@3.1.5 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @apollo/react-hooks@3.1.5 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @apollo/react-hoc@3.1.5 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @apollo/react-hooks@3.1.5 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @apollo/react-hooks@3.1.5 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @reactioncommerce/catalyst@1.19.1 requires a peer of react-dom@~16.9.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN mdi-material-ui@5.8.0 requires a peer of @material-ui/core@^1.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @reactioncommerce/components@0.69.0 requires a peer of react@~16.9.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @reactioncommerce/components@0.69.0 requires a peer of react-stripe-elements@~2.0.1 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @reactioncommerce/components@0.69.0 requires a peer of reacto-form@~1.4.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @reactioncommerce/components@0.69.0 requires a peer of styled-components@~3.3.3 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @reactioncommerce/eslint-config@2.2.0 requires a peer of eslint@>=7 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @reactioncommerce/eslint-config@2.2.0 requires a peer of eslint-plugin-jest@^23.13.1 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @reactioncommerce/eslint-config@2.2.0 requires a peer of eslint-plugin-node@^11.1.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @reactioncommerce/eslint-config@2.2.0 requires a peer of eslint-plugin-you-dont-need-lodash-underscore@^6.10.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @reactioncommerce/eslint-config@2.2.0 requires a peer of eslint-plugin-react-hooks@^4.0.2 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN frontend-collective-react-dnd-scrollzone@1.0.2 requires a peer of react-dnd@^7.3.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN graphql-tag@2.9.2 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN jss-camel-case@6.1.0 requires a peer of jss@^9.7.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN jss-compose@5.0.0 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN jss-default-unit@8.0.2 requires a peer of jss@^9.4.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN jss-expand@5.3.0 requires a peer of jss@^9.4.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN jss-extend@6.2.0 requires a peer of jss@^9.7.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN jss-global@3.0.0 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN jss-nested@6.0.1 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN jss-preset-default@4.5.0 requires a peer of jss@^9.7.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN jss-props-sort@6.0.0 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN jss-template@1.0.1 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN jss-vendor-prefixer@7.0.0 requires a peer of jss@^9.0.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN react-apollo@3.1.5 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN @apollo/react-hooks@3.1.5 requires a peer of @types/react@^16.8.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN react-sortable-tree@2.8.0 requires a peer of react-dnd@^7.3.0 but none is installed. You must install peer dependencies yourself.
reaction-admin_1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
reaction-admin_1  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
reaction-admin_1  | npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
reaction-admin_1  | npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
reaction-admin_1  | npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
reaction-admin_1  | npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
reaction-admin_1  | 
reaction-admin_1  | up to date in 7.108s
reaction-admin_1  | 
reaction-admin_1  | 113 packages are looking for funding
reaction-admin_1  |   run `npm fund` for details
reaction-admin_1  | 
reaction-admin_1  | npm verb exit [ 0, true ]
reaction-admin_1  | npm timing npm Completed in 7882ms
reaction-admin_1  | npm info ok 
reaction-admin_1  | Waiting for MongoDB...
reaction-admin_1  | MongoDB ready.
reaction-admin_1  | Waiting for MongoDB replica set...
reaction-admin_1  | MongoDB replica set ready.
reaction-admin_1  | (node:1) ExperimentalWarning: The ESM module loader is experimental.
reaction-admin_1  | Setting up plugin imports...
reaction-admin_1  | 
reaction-admin_1  | Failed to reset plugins file at /usr/local/src/app/client/plugins.js

**Comment by m5ingh** [comment] 2021-06-24 15:52
hey guys could anyone test [this pr](https://github.com/reactioncommerce/reaction-admin/pull/375)

**Comment by rondlite** [comment] 2021-09-29 21:49
@m5ingh @Akarshit I tested, works as expected but is made for 3.x Reaction, please merge trunk so can do proper test

**Comment by rondlite** [comment] 2021-09-29 22:16
Removing export from `docker-compose.dev.yml` solves the issue

**Closed as completed** 2021-11-17 16:23 UTC
Labels: needs triage
