### ISSUE TITLE
Error when trying to update a variant price

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-admin#91] opened 2019-11-22 22:13 UTC
I get the following error when trying to update the price on a variant. When I change the price, all the fields go blank. If I refresh, all of the fields return with their original values, including the price.

```
   { Error: Match failed [400]
    at errorClass.<anonymous> (packages/check/match.js:91:27)
    at new errorClass (packages/meteor.js:655:17)
    at check (packages/check/match.js:36:17)
    at MethodInvocation.products/updateProductField (imports/plugins/core/catalog/server/methods/catalog.js:127:5)
    at currentArgumentChecker.withValue (packages/check/match.js:118:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
     isClientSafe: true,
     error: 400,
     reason: 'Match failed',
     details: undefined,
     message: 'Match failed [400]',
     errorType: 'Meteor.Error' },
  errorType: 'Match.Error' }
```

**Comment by spencern** [comment] 2019-12-27 00:22
I'm seeing this as wel. It appears to happen after attempting to edit price multiple times, or after editing other variant fields.

**Comment by aldeed** [comment] 2019-12-30 00:37
API side issue is https://github.com/reactioncommerce/reaction/issues/5916

https://github.com/reactioncommerce/reaction/pull/5910 adds a way to set the price but we haven't yet updated the admin UI to use it.

**Comment by jrw421** [comment] 2021-01-20 19:41
Hi @mikemurray! We weren't able to reproduce this issue, and looks like this was fixed based on the conversations in reactioncommerce/reaction#5916 and reactioncommerce/reaction#5910. Going to close this one out, but please do reopen if you see this issue again. Thanks!

**Closed by jrw421** 2021-01-20 19:41 UTC
Labels: bug
