### ISSUE TITLE
React variables are visible

### ISSUE THREAD

**Issue by tanzeelazad95** [reactioncommerce/reaction-admin#309] opened 2020-08-12 10:26 UTC
We have followed the [Reaction Development Platform](https://docs.reactioncommerce.com/docs/installation-reaction-platform) to install Reaction.

## Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you able to consistently reproduce the issue?

## Issue Description
"The labels aren't loading all the time, it displays React variables. The issue exists in Chrome, firefox 
and safari."
[Screenshot](https://imgur.com/a/MEGtjeT)

## Steps to Reproduce
1. Login to reaction
2. Navigate the pages
3. Refresh the page

You will see that react variables are showing instead of labels. 
## Possible Solution
The labels should be shown on refreshing the page instead of react variables

### System information

- MAC OS Catalina
- Ubuntu 20.04 LTS

**Comment by kieckhafer** [comment] 2020-08-21 22:02
Thanks for the reported issue, @tanzeelazad95.

The `reaction-development-platform` repository is used to bootstrap the project and get it up and running, but issues regarding the API, Admin, Storefront, or anything outside the initial build are better suited in their respective project repositories.

I'm going to move this issue to the `reaction-admin` repo.

**Comment by kieckhafer** [comment] 2020-08-21 22:07
Hi @tanzeelazad95, what you are seeing are actually the [translations keys](https://github.com/reactioncommerce/reaction-admin/blob/trunk/imports/plugins/core/orders/client/components/OrdersTable.js#L38:L38), not React variables.

I am not able to reproduce:
![image](https://user-images.githubusercontent.com/4482263/90939236-6246e880-e3c8-11ea-937d-78bb3bc67889.png)

Be sure you have at least english translations available with those keys.

**Comment by ghost** [comment] 2020-09-05 01:16
I'm able to reproduce this issue by opening `beta.7` or `beta.9` and refreshing the page after clicking `Orders`:

<img width="1087" alt="Screen Shot 2020-09-05 at 09 14 34" src="https://user-images.githubusercontent.com/65664227/92293720-54f93480-ef58-11ea-8555-eac6c471b227.png">

It's a duplicate of #310 as both are caused due to a race condition/missing suspense for translation text.

**Comment by mian-muhammad** [comment] 2020-09-08 04:47
@kieckhafer I am also able to reproduce it in `reaction-admin v3.0.0-beta.8`
![Screenshot from 2020-09-08 09-45-56](https://user-images.githubusercontent.com/20898558/92434089-5032bb80-f1b8-11ea-82cb-df3bd9df7536.png)

**Comment by brent-hoover** [comment] 2020-09-08 06:55
fwiw I also see this issue when running this on the latest tip of `reaction-admin`. Sometimes it render correctly, sometimes not. Refreshing a few times usually works around it, but it seems to be clearly a race condition issue. (there are a ton of these in the latest admin)

**Closed as completed** 2021-02-15 20:59 UTC
Labels: bug, core work, verified reproducible
